### ISSUE TITLE
It would be great if baseline Sparse-RCNN code is added!

### ISSUE THREAD

**Issue by jongwook-Han** [bravezzzzzz/IoU-Enhanced-Attention#2]
Thank you for your great work and for sharing the code.

I want to reproduce the result of vanilla Sparse-RCNN stated in the paper.
It would be great if there is a code for baseline Sparse-RCNN.

Thank you

**Comment by bravezzzzzz** [comment]
Please refer to [SparseR-CNN](https://github.com/PeizeSun/SparseR-CNN).

**Comment by jongwook-Han** [comment]
Ah ha! Thank you for your reply.
